package com.skillengine.rummy.message;

public final class MessageConstants
{
	public final static String BOARD_INFO = "boardInfo";
	public final static String SEAT_INFO = "seatinfo";
	public final static String SEATS = "seats";
	public final static String USER_INFO = "userinfo";
	public final static String BOARD_SETUP = "boardSetup";
	public final static String PLAYER_TABLE_JOIN = "playerTableJoin";
	public final static String TABLE_CREATE = "tableCreation";
	public final static String GAME_STATUS = "gameStatus";
	public final static String GAME_SETUP = "gameSetup";
	public final static String GAME_TOSS = "gameToss";
	public final static String TOSS_INFO = "tossInfo";
	public final static String PLAYER_SEQ = "playerSequence";
	public final static String PLAYER_TURN = "playerTurnIntimation";
	public final static String PLAYER_TIME_OUT_DISCARD = "playerTimeOutDiscard";
	public final static String BOOT_OUT = "bootOut";
	public final static String PLAYER_TURN_OUT = "playerTurnOut";
	public final static String RESHUFFLE = "reshuffle";
	public final static String PICK_CLOSE_DECK = "pickCloseDeck";
	public final static String PICK_OPEN_DECK = "pickOpenDeck";
	public final static String PICK_OPEN_DECK_OUTBOUND = "pickOpenDeckOutBound";
	public final static String PICK_CLOSED_DECK_OUTBOUND = "pickClosedDeckOutBound";
	public final static String DISCARD = "discard";
	public final static String DISCARD_OUTBOUND = "discardOutBound";
	public final static String DECLARE_EVENT = "declareEvent";
	public final static String DECLARE_TIME_OUT = "declareTimeOut";
	public final static String FINISH = "finish";
	public final static String FINISH_PLAYER_TIMEOUT = "finishPlayerTimeOut";
	public final static String DEAL_WINNER = "dealWinner";
	public final static String FINISH_INIT = "finishInit";
	public final static String DECLARE_DETAILS = "declaringDetails";
	public final static String SCORE_UPDATE = "scoreUpdate";
	public final static String RESET_CARDS = "resetCards";
	public final static String DROP = "drop";
	public final static String DROP_RESPONSE = "dropResponse";
	public final static String WRONG_FINISH = "wrongFinish";
	public final static String DECLARE = "declare";
	public final static String DECLARE_SERVER = "declareServer";
	public final static String LEAVE_BOARD = "leaveBoard";
	public final static String REQUEST_DISCARD_CARDS = "reqDiscardCards";
	public final static String DISCARDED_CARDS = "discardedCards";
	public final static String FMG_REQUEST = "FMGReq";
	public final static String FMG_RESPONSE = "FMGResponse";
	public final static String UPDATE_SEAT_BALANCE = "updateSeatBalance";
	public final static String TABLE_RECON_REQ = "tableReconReq";
	public final static String SET_HAND_CARDS = "setHandCards";
}
